In [2]:
import numpy as np 
import pandas as pd
import sympy as sp

In [3]:
path='face feature vectors.csv'
rd=pd.read_csv(path)
df=pd.DataFrame(rd)
df

,Unnamed: 0,Unnamed: 1,0,1,2,3,4,5,6,7,...,118,119,120,121,122,123,124,125,126,127
0,1,male,-0.066420,0.151611,0.027740,0.052771,-0.066105,-0.041232,-0.002637,-0.158467,...,0.025989,-0.001087,0.027260,-0.046754,-0.118619,-0.163774,-0.000590,-0.076400,0.107497,0.001567
1,2,male,-0.030614,0.049667,0.008084,-0.050324,0.007649,-0.063818,-0.019530,-0.119905,...,0.044229,-0.023900,-0.028108,0.040618,-0.146579,-0.141244,0.016162,0.017638,0.080610,-0.015930
2,3,male,-0.096178,0.061127,0.035326,-0.035388,-0.090728,-0.018634,-0.024315,-0.139786,...,0.111141,0.059436,-0.029222,0.042115,-0.222173,-0.116908,0.093428,0.017391,0.057652,0.086116
3,4,male,-0.103057,0.085044,0.078333,-0.035873,-0.028163,0.004924,0.007829,-0.017016,...,0.100793,-0.002644,-0.023388,0.029497,-0.139830,-0.119243,0.005306,-0.015100,0.161575,0.062462
4,5,male,-0.125815,0.120046,0.023131,-0.042901,0.038215,-0.049677,-0.054258,-0.130758,...,0.090197,0.067527,0.039926,0.047469,-0.056852,-0.076700,0.004966,0.028171,0.026041,0.084135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,796,female,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
796,797,female,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
797,798,female,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
798,799,female,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
799,800,female,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

In [4]:
x=df.columns
print(x)

Index(['Unnamed: 0', 'Unnamed: 1', '0', '1', '2', '3', '4', '5', '6', '7',
       ...
       '118', '119', '120', '121', '122', '123', '124', '125', '126', '127'],
      dtype='object', length=130)

In [5]:
df=df.drop('Unnamed: 0',axis='columns')
df

,Unnamed: 1,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
0,male,-0.066420,0.151611,0.027740,0.052771,-0.066105,-0.041232,-0.002637,-0.158467,0.130467,...,0.025989,-0.001087,0.027260,-0.046754,-0.118619,-0.163774,-0.000590,-0.076400,0.107497,0.001567
1,male,-0.030614,0.049667,0.008084,-0.050324,0.007649,-0.063818,-0.019530,-0.119905,0.186553,...,0.044229,-0.023900,-0.028108,0.040618,-0.146579,-0.141244,0.016162,0.017638,0.080610,-0.015930
2,male,-0.096178,0.061127,0.035326,-0.035388,-0.090728,-0.018634,-0.024315,-0.139786,0.052211,...,0.111141,0.059436,-0.029222,0.042115,-0.222173,-0.116908,0.093428,0.017391,0.057652,0.086116
3,male,-0.103057,0.085044,0.078333,-0.035873,-0.028163,0.004924,0.007829,-0.017016,0.114907,...,0.100793,-0.002644,-0.023388,0.029497,-0.139830,-0.119243,0.005306,-0.015100,0.161575,0.062462
4,male,-0.125815,0.120046,0.023131,-0.042901,0.038215,-0.049677,-0.054258,-0.130758,0.173457,...,0.090197,0.067527,0.039926,0.047469,-0.056852,-0.076700,0.004966,0.028171,0.026041,0.084135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,female,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,0.030554,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
796,female,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,0.157421,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
797,female,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,0.165443,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
798,female,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,0.185083,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
799,female,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,0.048473,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

In [6]:
df_male=df.where(df['Unnamed: 1']=='male')
df_male=df_male.dropna()
df_male

,Unnamed: 1,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
0,male,-0.066420,0.151611,0.027740,0.052771,-0.066105,-0.041232,-0.002637,-0.158467,0.130467,...,0.025989,-0.001087,0.027260,-0.046754,-0.118619,-0.163774,-0.000590,-0.076400,0.107497,0.001567
1,male,-0.030614,0.049667,0.008084,-0.050324,0.007649,-0.063818,-0.019530,-0.119905,0.186553,...,0.044229,-0.023900,-0.028108,0.040618,-0.146579,-0.141244,0.016162,0.017638,0.080610,-0.015930
2,male,-0.096178,0.061127,0.035326,-0.035388,-0.090728,-0.018634,-0.024315,-0.139786,0.052211,...,0.111141,0.059436,-0.029222,0.042115,-0.222173,-0.116908,0.093428,0.017391,0.057652,0.086116
3,male,-0.103057,0.085044,0.078333,-0.035873,-0.028163,0.004924,0.007829,-0.017016,0.114907,...,0.100793,-0.002644,-0.023388,0.029497,-0.139830,-0.119243,0.005306,-0.015100,0.161575,0.062462
4,male,-0.125815,0.120046,0.023131,-0.042901,0.038215,-0.049677,-0.054258,-0.130758,0.173457,...,0.090197,0.067527,0.039926,0.047469,-0.056852,-0.076700,0.004966,0.028171,0.026041,0.084135
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,male,-0.129449,0.132177,0.055916,-0.009390,-0.080541,-0.072362,-0.067433,-0.192243,0.108654,...,0.142675,0.028204,-0.010465,0.002703,-0.117138,-0.148947,0.054327,0.004200,0.046730,0.037774
396,male,-0.158460,0.109948,0.019088,0.015506,-0.069668,0.032311,0.015062,-0.140817,0.141132,...,0.143453,0.059608,-0.006824,0.056758,-0.064352,-0.108518,0.132037,0.050347,0.071465,-0.022954
397,male,-0.101499,0.119739,0.016951,-0.013677,-0.055524,0.028399,0.028164,-0.152100,0.109814,...,0.046488,0.051044,-0.008298,0.018010,-0.164197,-0.122292,0.032616,-0.030194,-0.018642,0.032821
398,male,-0.149516,0.081588,0.090796,-0.053116,-0.133314,0.001096,0.019941,-0.117803,0.102320,...,0.111678,-0.016921,0.059115,-0.007810,-0.096824,-0.079415,-0.015487,-0.075470,0.062481,0.052727
399,male,0.039844,0.070357,0.130196,-0.007683,-0.077825,-0.021298,-0.024133,-0.085105,0.071288,...,0.105510,0.081928,-0.033337,-0.023604,-0.167003,-0.059075,0.053074,0.080940,0.011467,-0.021999

In [7]:
df_female=df.where(df['Unnamed: 1']=='female')
df_female=df_female.dropna()
df_female

,Unnamed: 1,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
400,female,0.001747,0.185678,0.073260,0.042142,-0.088674,0.028186,-0.027830,-0.064211,0.097413,...,0.123615,0.030036,0.041442,-0.012818,-0.119177,-0.165786,-0.075368,-0.017690,0.067028,0.036452
401,female,-0.091598,0.095340,0.072125,-0.092276,-0.079953,0.047782,-0.004701,-0.092005,0.222913,...,0.011370,0.144719,0.089139,-0.059767,-0.111235,-0.055420,0.006283,0.016900,-0.081676,0.022809
402,female,-0.018751,0.088572,0.068894,-0.065700,-0.115126,0.024339,-0.028420,-0.159320,0.164595,...,0.010345,0.095309,0.012255,-0.033010,-0.097720,-0.218889,0.077764,0.045943,0.010856,0.100522
403,female,-0.130889,0.093262,0.122244,-0.110014,-0.157625,-0.036781,0.073908,-0.098571,0.120419,...,0.003229,0.049330,0.059733,-0.023820,-0.098432,-0.034316,0.075131,-0.029204,-0.020707,0.031028
404,female,-0.037433,0.078158,0.118061,-0.117658,-0.194807,-0.045464,-0.014104,-0.158824,0.159272,...,0.043848,-0.009760,0.043486,0.020251,-0.115420,-0.040023,0.099409,-0.032240,0.037601,-0.020016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,female,-0.164731,0.064301,0.058630,-0.017420,-0.157600,-0.022536,0.002864,-0.072739,0.030554,...,0.095115,0.007198,-0.004655,0.023957,-0.170753,-0.136630,0.041614,0.031600,0.019064,0.004384
796,female,-0.095308,0.051095,0.092913,-0.101745,-0.083153,-0.028159,0.009090,-0.114513,0.157421,...,0.056078,0.119846,0.087470,0.017481,-0.096594,-0.084553,0.037709,0.030732,-0.083713,0.064970
797,female,-0.202852,0.037039,0.079731,-0.047156,-0.140062,-0.080246,0.057668,-0.122083,0.165443,...,0.066954,0.035684,-0.023112,-0.030452,-0.154243,-0.188270,0.071086,0.037384,-0.006257,0.039977
798,female,-0.088300,0.063530,0.049627,-0.026011,-0.172773,0.086218,0.042710,-0.161852,0.185083,...,0.039460,0.067547,0.040426,0.028007,-0.154515,-0.127736,0.046967,0.009701,-0.016942,0.048071
799,female,-0.156201,0.055165,0.142716,-0.115393,-0.128982,-0.139830,-0.037305,-0.101402,0.048473,...,0.024955,0.066980,-0.002332,-0.045738,-0.110557,-0.014995,-0.002124,-0.010298,-0.028856,0.075323

In [8]:
dfmale_train=df_male[:395]
dfmale_test=df_male[395:]
dffemale_train=df_female[:395]
dffemale_test=df_female[395:]

In [9]:
df_test=pd.concat([dfmale_test,dffemale_test])
df_test.head()

,Unnamed: 1,0,1,2,3,4,5,6,7,8,...,118,119,120,121,122,123,124,125,126,127
395,male,-0.129449,0.132177,0.055916,-0.009390,-0.080541,-0.072362,-0.067433,-0.192243,0.108654,...,0.142675,0.028204,-0.010465,0.002703,-0.117138,-0.148947,0.054327,0.004200,0.046730,0.037774
396,male,-0.158460,0.109948,0.019088,0.015506,-0.069668,0.032311,0.015062,-0.140817,0.141132,...,0.143453,0.059608,-0.006824,0.056758,-0.064352,-0.108518,0.132037,0.050347,0.071465,-0.022954
397,male,-0.101499,0.119739,0.016951,-0.013677,-0.055524,0.028399,0.028164,-0.152100,0.109814,...,0.046488,0.051044,-0.008298,0.018010,-0.164197,-0.122292,0.032616,-0.030194,-0.018642,0.032821
398,male,-0.149516,0.081588,0.090796,-0.053116,-0.133314,0.001096,0.019941,-0.117803,0.102320,...,0.111678,-0.016921,0.059115,-0.007810,-0.096824,-0.079415,-0.015487,-0.075470,0.062481,0.052727
399,male,0.039844,0.070357,0.130196,-0.007683,-0.077825,-0.021298,-0.024133,-0.085105,0.071288,...,0.105510,0.081928,-0.033337,-0.023604,-0.167003,-0.059075,0.053074,0.080940,0.011467,-0.021999

In [12]:
training=[dfmale_train,dffemale_train]
mean_vector=[]
cov_matirx=[]
cov_det=[]
for i in training:
    i=pd.DataFrame(i)
    t=i.drop('Unnamed: 1',axis='columns')
    mean=t.mean()
    mean=list(mean)
    mean_vector.append(mean)
    cov=t.cov()
    cov1=np.array(cov)
    cov2=sp.Matrix(cov1)
    det=cov2.det()
    cov_det.append(det)
    cov_matirx.append(cov1)

In [13]:
for i,j in zip(cov_det,mean_vector):
    print(i)

6.88031878312090e-863
6.52457334273817e-864

In [14]:
def gaussian(x, mean, cov,det):
    d = len(x)
    diff = x - mean
    exponent = -0.5 * np.dot(np.dot(diff.T, np.linalg.inv(cov)), diff)
    return (1.0 / ((2 * np.pi) ** (d / 2) * ((det)**0.5)))* np.exp(exponent)

In [15]:
outputs_test=df_test["Unnamed: 1"].values
outputs_test

array(['male', 'male', 'male', 'male', 'male', 'female', 'female',
       'female', 'female', 'female'], dtype=object)

In [16]:
df_test=df_test.drop('Unnamed: 1',axis='columns')
df_test=np.array(df_test)
df_test=list(df_test)

In [25]:
def prediction(r):
    x=''
    if(r==0):
        x='male'
    elif(r==1):
        x='female'
    return x

def check(r1,r2):
    acc=0
    for i,j in zip(r1,r2):
        if(i==j):
            acc+=1 
    leng=len(r1)
    return (acc/leng)*100

def check_class(r1,r2):
    acc=[]
    for j in range(2):
        x1=r1[5*j:5*(j+1)]
        x2=r2[5*j:5*(j+1)]
        acc_e=0
        for i,k in zip(x1,x2):
            if(i==k):
                acc_e+=1 
        leng=len(x1)
        t=acc_e/leng 
        t*=100
        acc.append(t)
    return acc[0],acc[1]
def discrminant(a):
    sp.symbols('c')
    c=a
    return sp.log(c)

p=1/2
predictions=[]
discrimininant=[]
for i in range(len(df_test)):
    distri=[]
    for j in range(2):
        t=gaussian(df_test[i],mean_vector[j],cov_matirx[j],cov_det[j])
        t*=p 
        distri.append(t)
    r=np.argmax(distri)
    dis=discrminant(distri[r])
    discrimininant.append(dis)
    pred=prediction(r)
    predictions.append(pred)
acc=check(predictions,outputs_test)
t1,t2=check_class(predictions,outputs_test)
print("Accuracy of the classifer is:",acc)
print("Accuracy of the classifer of male class is:",t1)
print("Accuracy of the classifer of female class is:",t2)
print("Discriminant function:")
for i in discrimininant:
    print(i)

Accuracy of the classifer is: 100.0
Accuracy of the classifer of male class is: 100.0
Accuracy of the classifer of female class is: 100.0
Discriminant function:
778.930731209160
785.281932844363
782.565329816357
774.717215698377
758.252574677279
759.126806058700
800.715208703780
775.726270792319
795.227749821742
782.059063507023